### ISSUE TITLE
One Xenium dataset on human breast cancer not in the database

### ISSUE THREAD

**Issue by kennethahah** [mahmoodlab/HEST#51] opened 2024-09-12 18:05 UTC
From the meta data `hf://datasets/MahmoodLab/hest/HEST_v1_0_2.csv`, I can't find the [Xenium data](https://www.10xgenomics.com/datasets/xenium-ffpe-human-breast-with-custom-add-on-panel-1-standard) published by 10X genomics on 2023-04-18. 

Do you have any concern not include this data into the database?

**Comment by guillaumejaume** [comment] 2024-09-12 18:08
I think it's a duplicate with a slightly different gene panel as https://www.10xgenomics.com/datasets/ffpe-human-breast-with-pre-designed-panel-1-standard

**Comment by guillaumejaume** [comment] 2024-09-12 18:09
Recent ones will be part of the next release. Stay tuned.

**Comment by pauldoucet** [comment] 2024-09-12 18:23
It should be a duplicate of TENX97, they both use the same 'hBreast_v1_AddOn100g' gene panel and tissue section, the only difference seems to be the software version.

**Closed** 2024-09-14 21:40 UTC
